# GitHub Actions Workflows to Add

## Instructions:
1. Go to https://github.com/Katzup/sentiment-edge-mobile/actions
2. Click "New workflow" → "set up a workflow yourself"
3. Create each file below with the exact name and content

---

## File 1: `.github/workflows/update-dashboard.yml`

```yaml
name: Update Static Dashboard

on:
  schedule:
    # Update dashboard every 5 minutes during market hours (9:30 AM - 4:00 PM EST)
    - cron: '*/5 14-21 * * 1-5'  # 9:30 AM - 4:00 PM EST (14:30-21:00 UTC)
  
  # Manual trigger
  workflow_dispatch:

jobs:
  update-dashboard:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install alpaca-py yfinance python-dotenv
        
    - name: Generate static dashboard
      env:
        ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
        ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
      run: |
        python generate_static_dashboard.py
        
    - name: Commit and push dashboard
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/index.html
        git diff --staged --quiet || git commit -m "📊 Update dashboard: $(date)"
        git push
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        force_orphan: true
```

---

## File 2: `.github/workflows/trading-automation.yml`

```yaml
name: SentientEdge Trading Automation

on:
  schedule:
    # 10:00 AM EST (15:00 UTC) - Pre-market analysis
    - cron: '0 15 * * 1-5'
    # 1:00 PM EST (18:00 UTC) - Midday session  
    - cron: '0 18 * * 1-5'
    # 3:30 PM EST (20:30 UTC) - Pre-close session
    - cron: '30 20 * * 1-5'
  
  # Allow manual triggers
  workflow_dispatch:
    inputs:
      session_type:
        description: 'Type of trading session'
        required: true
        default: 'manual'
        type: choice
        options:
        - manual
        - premarket
        - midday
        - preclose

jobs:
  trading-session:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Determine session type
      id: session-type
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "session_type=${{ github.event.inputs.session_type }}" >> $GITHUB_OUTPUT
        else
          # Determine session type based on time
          hour=$(date -u +%H)
          if [ "$hour" = "15" ]; then
            echo "session_type=premarket" >> $GITHUB_OUTPUT
          elif [ "$hour" = "18" ]; then
            echo "session_type=midday" >> $GITHUB_OUTPUT
          else
            echo "session_type=preclose" >> $GITHUB_OUTPUT
          fi
        fi
        
    - name: Run Enhanced Two-Tier Trading Session
      env:
        ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
        ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
        SESSION_TYPE: ${{ steps.session-type.outputs.session_type }}
      run: |
        python enhanced_two_tier_momentum.py
```

---

## Required GitHub Secrets

Go to Settings → Secrets and variables → Actions → New repository secret

Add these:
- **ALPACA_API_KEY**: Your Alpaca API key (PKU3ZF81H4OLIPPRLEUD)
- **ALPACA_SECRET_KEY**: Your Alpaca secret key

---

## Enable GitHub Pages

1. Go to Settings → Pages
2. Source: Deploy from a branch
3. Branch: main
4. Folder: /docs
5. Click Save

Your dashboard will be available at:
https://katzup.github.io/sentiment-edge-mobile/
