name: SentientEdge Trading Automation
on:
    schedule:
      - cron: '0 15 * * 1-5'
      - cron: '0 18 * * 1-5'
      - cron: '30 20 * * 1-5'
    workflow_dispatch:
      inputs:
        session_type:
          description: 'Type of trading session'
          required: true
          default: 'manual'
          type: choice
          options:
            - manual
            - premarket
            - midday
            - preclose
jobs:
    trading-session:
      runs-on: ubuntu-latest
      steps:
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install requests
        - name: Run trading session
          env:
            WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
            WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          run: |
            python -c "
            import os, requests, json
            from datetime import datetime
            data = {
                'session_type': 'github_test',
                'timestamp': datetime.now().isoformat(),
                'test': True
            }
            response = requests.post(
                os.getenv('WEBHOOK_URL'),
                json=data,
                headers={'X-Secret-Key': os.getenv('WEBHOOK_SECRET')},
                timeout=30
            )
            print(f'Success: {response.status_code}')
            "


          print(f'Webhook response: {response.status_code} {response.text}')
          "
