name: SentientEdge Trading Automation

  on:
    schedule:
      - cron: '0 15 * * 1-5'  # 10:00 AM EST
      - cron: '0 18 * * 1-5'  # 1:00 PM EST  
      - cron: '30 20 * * 1-5' # 3:30 PM EST
    workflow_dispatch:
      inputs:
        session_type:
          description: 'Type of trading session'
          required: true
          default: 'manual'
          type: choice
          options:
          - manual
          - premarket
          - midday
          - preclose

  jobs:
    trading-session:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install alpaca-py yfinance requests

      - name: Run trading session
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: |
          echo "🚀 Starting ${{ github.event.inputs.session_type || 'scheduled' }} trading session..."
          python -c "
          import os, requests, json
          from datetime import datetime

          # Simple trading data
          data = {
              'session_type': 'github_actions_test',
              'timestamp': datetime.now().isoformat(),
              'recommendations': [{'symbol': 'TEST', 'action': 'MONITOR'}],
              'analysis': {'platform': 'github_actions'},
              'performance': {'test': True},
              'orders': []
          }

          # Send webhook
          response = requests.post(
              os.getenv('WEBHOOK_URL'),
              json=data,
              headers={'Content-Type': 'application/json', 'X-Secret-Key': os.getenv('WEBHOOK_SECRET')},
              timeout=30
          )
          print(f'Webhook response: {response.status_code} {response.text}')
          "
