name: SentientEdge Trading Automation
on:
    schedule:
      - cron: '0 15 * * 1-5'
      - cron: '0 18 * * 1-5'
      - cron: '30 20 * * 1-5'
    workflow_dispatch:
      inputs:
        session_type:
          description: 'Type of trading session'
          required: true
          default: 'manual'
          type: choice
          options:
            - manual
            - premarket
            - midday
            - preclose
jobs:
    trading-session:
      runs-on: ubuntu-latest
      steps:
        - name: Install dependencies
          run: pip install requests
        - name: Send webhook
          env:
            WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
            WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          run: |
            curl -X POST "$WEBHOOK_URL" \
              -H "Content-Type: application/json" \
              -H "X-Secret-Key: $WEBHOOK_SECRET" \
              -d '{"session_type":"github_test","timestamp":"'$(date -u +%Y-%m-%dT%H:%M:%S)'","test":true}'

